title: 'wickedlyethan'
theme: 'indexhibit'

publishDir: 'docs'

baseURL: 'https://ethanthibault.com/'
languageCode: 'en-us'
enableRobotsTXT: false

disableKinds: ["RSS", "sitemap", "taxonomy", "term"]

menus:
  main:
    - name: Blog
      pageRef: /blog
    - name: Photos
      pageRef: /photos
    - name: Notes
      pageRef: /notes
    - name: Recipebook
      pageRef: /recipes  

# https://gohugo.io/getting-started/configuration/#configure-dates
frontmatter:
  date:
  - :filename
  - :default

permalinks:
  blog: /blog/:year/:month/:slug/

Params:
  author: ''
  description: ''
  dateFormat: "2006-01-02"

markup:
  goldmark:
    renderer:
      unsafe: true