title: 'wickedlyethan'
theme: 'indexhibit'
Params:
  author: ''
  description: "Wickedlyethan's personal website and garden"
  dateFormat: "2006-01-02"

menus:
  main:
    - name: Blog
      pageRef: /blog
    - name: Photos
      pageRef: /photos
    - name: Notes
      pageRef: /notes

permalinks:
  blog: /blog/:year/:month/:slug/

publishDir: 'docs'

baseURL: 'https://wickedlyethan.com/'
languageCode: 'en-us'
enableRobotsTXT: false

disableKinds: ["RSS", "sitemap", "taxonomy", "term"]

# https://gohugo.io/getting-started/configuration/#configure-dates
frontmatter:
  date:
  - :filename
  - :default

markup:
  goldmark:
    renderer:
      unsafe: true